[GLOBAL]
TIEMPO_REFRESCO_SEGUNDOS = 30
USUARIOS_OCULTOS = root, mngsrv
PROCESOS_MONITOREADOS = apache2, nginx, sshd, python3

[VISIBILIDAD_SECCIONES]
server_info = YES
storage = YES
cpu = YES
ram = YES
swap = YES
network = YES
security_metrics = YES
users_online = YES
processes = YES

[VISIBILIDAD_SUBSECCIONES]
monitored_services = YES
top_3_consumers = YES

[VISIBILIDAD_SECCIONES]
storage = true

[VISIBILIDAD_SUBSECCIONES]
storage_mounts = true